### ISSUE TITLE
Create the directories for the output target if it doesn't exist

### ISSUE THREAD

**Issue by lewisf** [apollographql/apollo-cli#172]
When using --output, if the desired output directory doesn't exist, we can make the directories automatically. This would make integration with other tools/processes easier

**Comment by alamothe** [comment]
Does `--output` take a directory or file? Running:

    apollo-codegen generate --help
    # ...
      --output                                 Output directory for the generated
                                               files                        [string]
    # ...

Suggests it is a directory, but it cannot handle anything other than a file (at east for TypeScript target)
