### ISSUE TITLE
Proposal: Generate distinct files as siblings to each query, rather than a single file with all types in it

### ISSUE THREAD

**Issue by blargity** [apollographql/apollo-cli#218]
## Use Case

We're using Apollo Codegen on our code base and it's great! The only persistent frustration we have is that we need to namespace all our queries to their area of the system so that we can pull in the right type.

In our code base, quite often, different chunks of code need to operate slightly differently, so creating a generic mutation called `CreateAccount` or similar doesn't often work for us. We instead need to have `AccountsManager_CreateAccount` which then of course becomes `AccountsManager_CreateAccountQuery`. Our longest type name is currently `AccountsManagerFetchTransactionsByDateQueryVariables` which is pretty long.

Although we're just getting started building, we can see this becoming very difficult to manage at a larger scale.

## Additional Info

We're using Typescript and generating to a `schema.ts` file. Our queries are in `.gql` files spread throughout the code base.

## Proposed Change

I'd like to change Apollo Codegen so that it has an option to generate files alongside the queries it finds. Rather than a single file containing all types, we could then import the types from the queries themselves.

Here's what it looks like today:
```
import { AccountsManagerFetchCheckpointsByValidUpToQuery } from 'core/schema';
import * as fetchCheckpointsByValidUpTo from './fetch-checkpoints-by-valid-up-to.gql';

...etc...
```

And here's what I'd like it to look like:

```
import { FetchCheckpointsByValidUpToQuery } from './fetch-checkpoints-by-valid-up-to';
import * as fetchCheckpointsByValidUpTo from './fetch-checkpoints-by-valid-up-to.gql';
```

So effectively, Apollo Codegen would generate `file-name.ts` for every `file-name.gql` it finds in the code base as a sibling alongside the original file.

I'd be happy to make these changes myself but noticed the Contributing guide and figured I'd better get alignment on whether this is a good thing to do or not, the best approach to take, as well as understand the complete set of things I'd need to support in order to get the changes merged.

Any feedback would be welcome!

**Comment by j** [comment]
Any info on this?

**Comment by shadaj** [comment]
This is supported by Apollo CLI when passing in a directory as the output. All types will be placed with a relative path inside the directory that matches the path to the original query.

**Comment by asfernandes** [comment]
The files are not emitted in the directory with a relative path. The files are just flat placed in the directory.

And a single file with many graphql queries are emitted as multiple ts files in that directory.

It's difficult to maintain a large project in this way.

**Comment by jamesdh** [comment]
@shadaj I just tried what you suggested here, and not only did it not place the files inside a relative path matching the original query, but it also deleted all other files within that directory, effectively wiping out half a days uncommitted work. 

Anyone who stumbles upon this in the future...be warned :(
