### ISSUE TITLE
Support for.graphql/yaml schemas

### ISSUE THREAD

**Issue by arthens** [apollographql/apollo-cli#259]
We are writing a client for a backend that only provides provides `schema.graphql` (extracted using https://github.com/graphcool/graphql-cli ) and no `schema.json`, but if we try to use this schema with apollo-codegen we get a parse error

```
> apollo-codegen generate src/**/*.graphql --schema schema.graphql --target typescript --output schema.ts

(function (exports, require, module, __filename, __dirname) { schema {
                                                                     ^
SyntaxError: Unexpected token {
```

Does `apollo-codegen` only support JSON schemas? Any plan to support `.graphql` schemas in future?

**Comment by martijnwalraven** [comment]
You can convert a `schema.graphql` schema file to `schema.json` using:
```shell
apollo-codegen introspect-schema schema.graphql --output schema.json
```

But it probably makes sense to support `schema.graphql` as is, especially as more tools start supporting it. We may also want to integrate with `graphql-cli` directly.

**Comment by arthens** [comment]
> But it probably makes sense to support schema.graphql as is, especially as more tools start supporting it.

This would be nice, particularly because the `.graphql` is more human readable.

> We may also want to integrate with graphql-cli directly.

Their `-w` is quite handy. It'd be nice to be able to say "poll for the schema and run apollo-codegen if the schema has changed".

**Comment by mike-marcacci** [comment]
Another really clean solution would be to let `introspect-schema` write to `stdout` and let `generate` read from `stdin`; that way you could easily pipe them together.
