### ISSUE TITLE
Is it possible to add --watch parameter to 're-generate' types on every file change?

### ISSUE THREAD

**Issue by pie6k** [apollographql/apollo-cli#289]
I think it'd be good dev-experience:

1. I write some query using `gql` in my eg. React component. 
2. I save the file
3. I'm instantly able to import just created query type interface that was just generated.

**Comment by martijnwalraven** [comment]
Yeah, I agree, that is definitely the experience we'd want. I'd like to move features out of `apollo-codegen` and into a common package we can share with other tools however, and this also seems like a good candidate for that. We may also be able to integrate with [graphql-language-service](https://github.com/graphql/graphql-language-service).

**Comment by FredyC** [comment]
Any progress on this? I don't have anything to contribute right now, but it would be lovely to have something that.

**Comment by bmayen** [comment]
We're currently doing this by starting a fs watch in npm scripts. The problem is, we're using gql literal tags in our ts so we have to watch **/*.ts and regenerate on every file change, even if no graphql stuff actually changes. Would be really nice if this could instead be handled intelligently by codegen.

**Comment by martijnwalraven** [comment]
We're starting to look into this, and I have some experimental code that I need to get in better shape first, but I definitely hope we can make this part of codegen.

**Comment by pie6k** [comment]
Hey @martijnwalraven , do you think it can be implemented anywhere soon?

**Comment by pie6k** [comment]
I don't want to look insistent, but it'd be really cool to have it @martijnwalraven :)

**Comment by ntziolis** [comment]
Checkout the `graphql-cli` which comes with the `graphql codegen` command (which uses apollo-codegen underneath) +  supports watching as well. So while its NOT apollo doing the watching, it will trigger apollo  on file change which is what you are looking for I assume.

**Comment by alexk111** [comment]
Would be really awesome to have the watch in apollo-cli! If there is some blocking issue with implementing it or any help needed please let the community know :)
