### ISSUE TITLE
Feature Request: Separate code generation API from file-writing

### ISSUE THREAD

**Issue by erydo** [apollographql/apollo-cli#323]
Currently the `apollo-codegen` package exports a `generate` function. That function does some validation, compilation, calls the sub-generators, and writes the output files.

It would be helpful to split these steps up and expose an API for returning the generated contents. That would make it easier to e.g. post-process or inline generated type definitions, or customize directory layout, without having to choose between juggling files or duplicating the logic of the `generate` module.

Related:
  * #322 _Flow Modern ignores output path and writes generated files next to input queries_

**Comment by lewisf** [comment]
@erydo the CLI API itself is largely unchanged from when this tool was first created. I agree it could be better -- let me think about this a bit.

i'd like a little bit more definition around this task -- what is your use case around "post-process or inline generated type definitions"

if the existing directory layout doesn't work, what would you prefer instead?

**Comment by shadaj** [comment]
This has been fixed with the recent restructuring.
