### ISSUE TITLE
ts-modern creates .js files

### ISSUE THREAD

**Issue by sgoll** [apollographql/apollo-cli#343]
It seems that `ts-modern`/`typescript-modern` creates `.js` files instead of the expected `.ts` files inside the `__generated__` colocation folders.

Since the files are to be used by TypeScript, they must have the `.ts` extension instead.

**Comment by rasdaniil** [comment]
monkey patching:
`node_modules/apollo-codegen/lib/javascript/typescript/codeGeneration.js`
lines 53, 62

**Comment by patrick91** [comment]
Looks this is has been fixed already, but not released: https://github.com/apollographql/apollo-codegen/compare/v0.18.3...master

**Comment by patrick91** [comment]
Temporary workaround, in package.json:


```
{
  "scripts": {
    "postinstall": "sed -i '' \"s/\\.js\\`/\\.ts\\`/\" node_modules/apollo-codegen/lib/javascript/typescript/codeGeneration.js",
    "graphql-schema": "apollo-codegen introspect-schema http://localhost:4000/graphql --output schema.json",
    "graphql-queries": "apollo-codegen generate --target typescript-modern --tag-name graphql --schema schema.json `find ./src -name *.graphql`"
  }
}
```
