### ISSUE TITLE
Scala (not ScalaJS) target

### ISSUE THREAD

**Issue by inakianduaga** [apollographql/apollo-cli#353]
We want to consume graphQL apis from within Scala backends. We are currently resorting to "misusing" the scalaJS generated code for the data types only and removing the `extends com.apollographql.scalajs.GraphQLQuery` reference, which we don't need.

It should be possible to provide an option to the scala codegen target to ommit the ScalaJS extension so the data types can be used

**Comment by joseph-whiting** [comment]
Indeed this is relevant to anyone who just wants to use a different ScalaJS framework like scalajs-react or bindings.scala.

**Comment by inakianduaga** [comment]
I've been testing this and it seems to do what I was looking for

https://github.com/muuki88/sbt-graphql

not perfect (graphql interfaces are not handled ideally) but it's a start.

I'll close the issue for now
