### ISSUE TITLE
Typescript schema types: Semicolons after interfaces cause errors

### ISSUE THREAD

**Issue by ChrisGitter** [apollographql/apollo-cli#385]
Using apollo-codegen 0.18.8 and typescript 2.7.2, I get the following error from Typescript:

`[ts] Statements are not allowed in ambient contexts.`

The error is caused by the semicolon inserted after the interfaces in the schema.d.ts file, for example:
`export interface InterfaceName {
  ...
};`

Is there any CLI option to avoid the generation of semicolons?

**Comment by daggerjames** [comment]
+ 1. manually deleting semicolon kills me.

**Comment by TiuSh** [comment]
Same here, with Typescript 2.6.2.

@lewisf Could we just remove the `generator.print(';');` from [here](https://github.com/apollographql/apollo-codegen/blob/master/src/typescript/language.ts#L46) ? That should fix this issue, but I don't know the exact impact on previous typescript version.

**Comment by lewisf** [comment]
@TiuSh I don't use Typescript on my day to day graphql repo. Can someone confirm that this is okay?

**Comment by TiuSh** [comment]
@lewisf After a little digging, it seams that Typescript interfaces should not be followed by semicolon (see https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md for more examples). I created a PR with the given fix and updated tests.

**Comment by zhenwenc** [comment]
A funny workaround, I run prettier on the generated file to remove the semicolon ...

**Comment by shadaj** [comment]
With the new TypeScript target in the Apollo CLI, semicolons are no longer added after interfaces!
