### ISSUE TITLE
Git not found in path error when publishing a schema to Apollo Engine

### ISSUE THREAD

**Issue by unicodeveloper** [apollographql/apollo-cli#4]
I get this error when I try to publish a schema to Apollo Engine via the CLI.

<img width="1150" alt="screen shot 2018-06-26 at 8 47 20 am" src="https://user-images.githubusercontent.com/2946769/41908849-4c55b210-793d-11e8-9a50-d4727cf22dad.png">

This error goes away when I eventually run `git init` to initialize a new empty git directory.

Is this the ideal functionality?

**Comment by jbaxleyiii** [comment]
This should be fixed in `1.0.6`, thanks for the report!
