### ISSUE TITLE
Wrapper over apollo-codegen

### ISSUE THREAD

**Issue by Beniamiiin** [apollographql/apollo-cli#401]
Hey guys. I have been using this tool for my project and I faced a few problems. So I decided to write a [wrapper](https://github.com/Beniamiiin/Apollo-Codegen-wrapper) over `apollo-codegen`.

### Reasons why I did it

With the original tool so difficult to store fragments and requests in different files because it can't generate them, actually can but with big problems.
The original tool generates all fragments and all requests in one API.swift file. It's not a good idea because it's not comfortable and maybe in one day Xcode can't open this file or you will face delays during scrolling.

Maybe it will be useful for someone, welcome🤙

Link: https://github.com/Beniamiiin/Apollo-Codegen-wrapper

**Comment by shadaj** [comment]
The Apollo CLI now supports output splitting, which should fix issues with large generated files!
