### ISSUE TITLE
Feature request: use docstring comment syntax in generated TypeScript types

### ISSUE THREAD

**Issue by meyer** [apollographql/apollo-cli#417]
I love that `apollo-codegen` prepends GraphQL field descriptions as comments to types. If the comments were written using docstring syntax, they’d show up in context in editors that support it (VS Code, for example).

Before:

```js
// number of pages in the collection
count: number | null;
```

After:

```js
/** number of pages in the collection */
count: number | null;
```

If that’s something you all are interested in, let me know and I’ll whip up a PR. Should be pretty straightforward.

**Comment by meyer** [comment]
whoa, i just noticed `typescript-modern` is a thing. Innnnteresting. No mention of it anywhere in the README.

**Comment by fbartho** [comment]
@meyer Did you see: #441 :-(

**Comment by shadaj** [comment]
This is fixed in Apollo CLI!
