### ISSUE TITLE
0.20.1 does not provide `typescript-legacy` target when installed with yarn/npm

### ISSUE THREAD

**Issue by jbbr** [apollographql/apollo-cli#448]
Steps to reproduce:

```bash
# in an empty directory
$ yarn init
$ yarn add apollo-codegen@0.20.1
$ yarn run apollo-codegen

$ yarn run apollo-codegen generate some.graphql --target typescript-legacy --output out.ts

error: Invalid values:
  Argument: target, Given: "typescript-legacy", Choices: "swift", "scala", "json", "ts", "ts-modern", "typescript", "typescript-modern", "flow", "flow-modern"

```

Error:
```
error: Invalid values:
  Argument: target, Given: "typescript-legacy", Choices: "swift", "scala", "json", "ts", "ts-modern", "typescript", "typescript-modern", "flow", "flow-modern"
```

It seems as if the published code is not actually 0.20.1 - some features seem to be broken or missing.
Documented behavior vor 0.20.0+ is not available. e.g using `ts-modern` or `ts` with output to directory does not work. But `cli.js` requires `output` argument (Which is a breaking 0.20.0 change).

Not sure what other infos I could provide to help fixing this. I assume there might have been a problem with the distributed version to npm, e.g. generation of JS from TS codebase.
So probably republishing this version would fix this.

**Comment by lirbank** [comment]
Yes, providing `--target typescript` does seem to use legacy-ts for sure - `--target typescript-modern` still works though.

**Comment by jbbr** [comment]
Yes, but that's not the documented behavior for `0.20.1`.
Also it's very odd that `apollo-codegen@0.20.0` has the new `typescript-legacy` target and `apollo-codegen@0.20.1` has `typescript-modern` and not `typescript-legacy`.

Looks like there went something wrong while publishing that version.

**Comment by jcready** [comment]
@shadaj you broke stuff, please fix.

**Comment by shadaj** [comment]
We have moved the codegen features into the Apollo CLI, which will contain future fixes and features for code generation.

For an immediate fix, `apollo-codegen` 0.20.2 has been released which has working legacy targets.

**Comment by jcready** [comment]
> We have moved the codegen features into the Apollo CLI, which will contain future fixes and features for code generation.

Then perhaps a major version bump would've been appropriate.

You also broke the `typescript` target which was supposed to use the `typescript-modern` generator, but instead used the legacy version. Was that fixed in your 0.20.2 release?

**Comment by shadaj** [comment]
The Apollo CLI is versioned separately, with a separate major version (the latest release is `1.1.1`).

The `0.20.2` release matches the CHANGELOG. `typescript` refers to the `typescript-modern` generator and `flow` refers to the `flow-modern` generator. The `0.20.1` release was built from the wrong sources by mistake.

**Comment by jcready** [comment]
You know you _can_ unpublish a broken version from npm, right?

**Comment by shadaj** [comment]
The issue with the package was discovered > 24 hours after it was published, so NPM doesn't easily allow unpublishing it (https://docs.npmjs.com/cli/unpublish).
