### ISSUE TITLE
cannot find module @bable/types

### ISSUE THREAD

**Issue by zifahm** [apollographql/apollo-cli#482]
Had apollo cli as global install
ran apollo schema:download       //    there was no errors
ran apollo codegen:generate   //Error: Cannot find module '@babel/types'
    at Object.<anonymous> (~/Documents/app/node_modules/apollo-codegen-flow/lib/codeGeneration.js:3:11)

so i installed apollo-codegen as dev dependency 
then ran apollo codegen:generate  and it ran with no error

before when it was typescript 2.9.1  the above command with no apollo-codegen as dev dependency ran  with no problem. with new typescript 2.9.2 this was the error I got? 
something to look at!

**Comment by Andyparr** [comment]
I'm also having this same problem, some help would be amazing :) thank you

**Comment by zifahm** [comment]
@Andyparr  i installed apollo-codegen and it worked again fine

**Comment by shadaj** [comment]
Fixed by https://github.com/apollographql/apollo-cli/pull/499!
