### ISSUE TITLE
Issue with typescript type generation - differing behavior between flow and typescript

### ISSUE THREAD

**Issue by mwarger** [apollographql/apollo-cli#527]
#### Reproduction
Typescript: https://github.com/mwarger/parcel-typescript-graphql-gen-example
Flow: https://github.com/mwarger/parcel-flow-graphql-gen-example

Please clone the two projects and run `npm install`.

Run `npm run download-schema` and then `npm run generate-types` for each project.

#### Issue
Please note the difference between the differing output between the two.  Flow seems accurate, and Typescript seems... incomplete.

The two Queries are found in `index.js` and `App`.  

The only difference is the `--target` flag.  

I believe there's a problem with typescript generation.  Please let me know if you have any questions.

#### Source files in `/graphql-types` after generation:

For typescript, I get one output file called GetRates (I would expect to see another one for CurrencyRates):
```javascript
export interface GetRates_rates {
  __typename: "ExchangeRate";
  currency: string | null;
}

export interface GetRates {
  rates: (GetRates_rates | null)[] | null;
}
```

For flow, I get two output files (one for each query, as I would expect):
One called GetRates:
```javascript
export type GetRates_rates = {
  __typename: "ExchangeRate",
  currency: ?string,
};

export type GetRates = {
  rates: ?Array<?GetRates_rates>
};
```
and one called CurrencyRates:
```javascript
export type CurrencyRates_rates = {
  __typename: "ExchangeRate",
  currency: ?string,
  rate: ?string,
};

export type CurrencyRates = {
  rates: ?Array<?CurrencyRates_rates>
};
```

**Comment by danilobuerger** [comment]
It makes sense if you look at your `generate-types`:
```
apollo codegen:generate graphql-types --addTypename --queries=src/**/*.js --schema=./schema.json --target=typescript
```

As you specified in the queries options, it should look at files ending in `.js`. `App.tsx` does not end in `.js`. Therefor, correctly, it is ignored by `codegen:generate`.

**Comment by mwarger** [comment]
Thanks for pointing out my silly mistake!
