### ISSUE TITLE
Is apollo-vscode published?

### ISSUE THREAD

**Issue by lirbank** [apollographql/apollo-cli#542]
Has the VS Code plugin been published? 

The [docs](https://github.com/apollographql/apollo-cli/tree/master/packages/apollo-vscode#how-to-get-it) say:

> How to get it?
> Open up VS Code and search for the extension "Apollo".

But it does not seem to be there:
![image](https://user-images.githubusercontent.com/2538130/43975937-114cd1ce-9c94-11e8-8d90-c841e88ef5ea.png)

**Comment by shadaj** [comment]
Hi, we're still working on a bit more fine tuning before we launch the extension officially. We'll have a post on the Apollo GraphQL blog when it's available!

**Comment by Aleksion** [comment]
My goto Graphql extensions has stopped working, so I'm very eager to see this one come out :D... Any ETA on it? (I'd love to test it for you guys ;) )

**Comment by cmcaboy** [comment]
It is available now. I am using it.
