### ISSUE TITLE
[Critical] Invalid reference to globalTypes.ts

### ISSUE THREAD

**Issue by lirbank** [apollographql/apollo-cli#543]
The import of global types in each file looks is missing a file path:

`import { SomeInput } from "globalTypes";`

It should have a leading `./` for the import to work, eg:

`import { SomeInput } from "./globalTypes";`

I am using this command:

```
apollo codegen:generate --queries=\"src/**/*.{ts?(x),graphql}\" --schema=schema.json --clientSchema=clientSchema.graphql --target=typescript --addTypename --tagName=gql --outputFlat src/__generated__/
```

I really like how you moved all input types to a shared file!

**Comment by lirbank** [comment]
I am using "apollo": "1.7.0",

**Comment by shadaj** [comment]
Hi, this is definitely a bug. Investigating now!

**Comment by kgtkr** [comment]
When will a modified version of this be released?

**Comment by lirbank** [comment]
@shadaj awesome that you found the bug! When do you think you'll be pushing a new release? Anxious to get my hands on all the new features in 1.7.x
