### ISSUE TITLE
TypeError: Cannot read property 'extends' of undefined

### ISSUE THREAD

**Issue by janhartmann** [apollographql/apollo-cli#647]
I am trying to download the schema and generate some types using Apollo 1.9.2. First of all, here is my ´apollo.config.js`

```
module.exports = {
  schemas: {
    myEndpoint: {
      endpoint: "https://my-endpoint.com/graphql"
    }
  }
};
```

Then I am running this command to fetch my schema from the endpoint:

`apollo schema:download ./src/data/schema.json`

This saves a `schema.json` in the correct folder and it has the schema content.

Then I run 

`apollo codegen:generate __generated__ --schema=./src/data/schema.json --target=typescript`

Which gives me the following error:

```
$ apollo codegen:generate __generated__ --schema=./src/data/schema.json --target=typescript
 ✔ Loading Apollo config
 ✖ Resolving GraphQL document sets and dependencies
   → Cannot read property 'extends' of undefined
   Generating query files
TypeError: Cannot read property 'extends' of undefined
    at resolveSchema (/usr/local/lib/node_modules/apollo/lib/config.js:123:27)
    at Promise.all.map (/usr/local/lib/node_modules/apollo/lib/config.js:145:25)
    at Array.map (<anonymous>)
    at Object.resolveDocumentSets (/usr/local/lib/node_modules/apollo/lib/config.js:131:53)
    at Task.task (/usr/local/lib/node_modules/apollo/lib/commands/codegen/generate.js:83:55)
    at Promise.resolve.then.then.skipped (/usr/local/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by janhartmann** [comment]
Apperently this can be resolved by removing the `apollo.config.js` and just using `--endpoint=https://my-endpoint.com/graphql´. Now I just get another error `GraphQLError: Cannot query field "machines" on type "Query"` which I need to file on another issue.

**Comment by lednhatkhanh** [comment]
Did you find a solution for this?
